name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }} > ${{ secrets.GOOGLE_CREDENTIAL_FILE_NAME }}
          docker build -t google-vision:latest .

      - name: Configure Docker credentials
        env: 
          ARTIFACT_REGISTRY_URL: ${{ secrets.GCP_ARTIFACT_REGISTRY_URL }}
        run: |
          docker login -u _json_key --password-stdin $ARTIFACT_REGISTRY_URL < ${{ secrets.GOOGLE_CREDENTIAL_FILE_NAME }}

      - name: Push the Docker image
        env: 
          ARTIFACT_REGISTRY_URL: ${{ secrets.GCP_ARTIFACT_REGISTRY_URL }}
        run: |
          docker tag google-vision:latest $ARTIFACT_REGISTRY_URL/google-vision:latest
          docker push $ARTIFACT_REGISTRY_URL/google-vision:latest
