name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create credential file and .env file
        run: |
          echo "APPLICATION_ENV=production" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t google-vision:latest .

      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Push the Docker image
        env: 
          ARTIFACT_REGISTRY_URL: ${{ secrets.GCP_ARTIFACT_REGISTORY_URL }}
        run: |
          docker tag google-vision:latest $ARTIFACT_REGISTRY_URL/google-vision:latest
          docker push $ARTIFACT_REGISTRY_URL/google-vision:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
          
      # deploy to cloud run 
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_name: "google-vision"  # Replace with the name of your existing Cloud Run service
          image: ${{ secrets.GCP_ARTIFACT_REGISTORY_URL }}/google-vision:latest
          platform: "managed"
          region: ${{ secrets.REGION }}
          service: google-vision  # Add the service argument to specify the Cloud Run service name
        
